### ISSUE TITLE
Soft reboot issue

### ISSUE THREAD

**Issue by Moderndaycowboy** [waylaidwanderer/PowerNapForXposed-Development#7] opened 2016-10-26 22:45 UTC
I make nap for Android system and Google play, while I was talking with someone, the sensor shuts the screen, powernap understands that situation a state of locked phone. İf I do that screen off and screen on with my cheek via sensor, the phone goes to soft reboot.

**Comment by waylaidwanderer** [comment] 2016-10-26 23:00
Duplicate of #1, already solved for future update

**Closed as completed by waylaidwanderer** 2016-10-26 23:00 UTC
