### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by ghost** [waylaidwanderer/PowerNapForXposed-Development#13] opened 2016-11-03 04:18 UTC
Seems around 40ish% battery powernap starts crashing my gui then my system causing a soft reboot
(This also would have been inside of the low battery activation threshold I had set)
Samsung Galaxy S5 G900T
Stock Touch wiz 6.0.1
Arm Based 32 bit processor

**Comment by ghost** [comment] 2016-11-03 04:19
Might I add it's repetitive

**Comment by waylaidwanderer** [comment] 2016-11-03 05:06
Duplicate of #8

**Closed as completed by waylaidwanderer** 2016-11-03 05:06 UTC
